### ISSUE TITLE
kr1 - alpha 2 issues

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1085]
## High Prio
- [x] game crashes on entering ice stages (coldstep mines, icewind pass, stormcloud temple, sarelgaz's lair, glacial heights, ha'kraj plateau) #1093
```
Error: ./all/systems.lua:1511: attempt to perform arithmetic on local 'a' (a nil value)
stack traceback:
        ./all/systems.lua:1511: in function 'phase_interp'
        ./all/systems.lua:1652: in function 'on_update'
        ./all/simulation.lua:121: in function 'do_tick'
        ./all/simulation.lua:92: in function 'update'
        ./all/game.lua:277: in function 'update'

```
- [x] missing translations #1089
- [x] sheep missing texture #1086
- [x] Thor - hammer throw damage is different from cocos. It is 50 or 60 / 70 or 80 / 90 or 120 in cocos. #1095 
- [x] low quality tower taunts #1094 
  - they were recompressed... need to check!
- [x] thorn mod -facing direction (http://imgur.com/gallery/u1Ou5pS.mp4)
- [x] Hero sound clips with noise
  - Gerald Holy-Paladin-Death
  - Gerald Holy Paladin-01c
  - Bolin Dwarf-Rifleman-04c
  - Malik Reinforcement-Death_c
  - Magnus Young-Mage-01d
  - Magnus Young-Mage-02a
  - Magnus Young-Mage-03c
  - Magnus Magnus Young-Mage-04c
  - Magnus Young-Mage-Death_c
- [x] Ice stages: add snowing fx from Unity 
- [x] level 1 campaign - "hero at your command" hint pops up at intro.
- [x] #1084 - Sunray tower i18n
- [x] enemy cards and tower cards use low-resolution pictures.
- [x] Pool spawns husks even if soldiers (ancestors and reinforcements) disappear without being killed. #1087
- [x] Ingvar's bearform duration is fixed at 12 seconds at all levels.
  - correct in 4.0.02
- [x] Pit of Fire campaign - Cerberus disappears at the intro of the last wave.
https://streamable.com/lhoeb
- [x] When a tower or a holder is selected, it isn't highlighted in yellow ring.
- [x] Artillery tower prices and ability prices after discount upgrades are different from cocos.
Level 1 artillery: 113 (love) to 112 (cocos)
Tesla: 338 to 337
Overcharge: 188/94/94 to 187/93/93
Supercharged Bolt: 188/188 to 187/187
Dragonbreath Launcher: 188/75/75 to 187/75/75
Cluster Launcher Xtreme: 188/113/113 to 187/112/112
- [x] Big Bertha - The damage values are wrong. It is 100-50 (and 111-56 after Concentrated Fire is upgraded). Min number should come first. And, the upgraded damage should be 55-110.
- [x] Concentrated Fire - with this upgraded, Tesla's damage changes to 66-122. It is 66-121 in cocos.
- [x] Demon Legion's clone gives gold, too.
- [x] The Wastes graveyard spawner - game declares victory before the last skeleton spawn is killed. https://cdn.discordapp.com/attachments/567811170342535188/672008123359166484/2020_01_29_18_10_58_968_new.mp4
- [x] Arcane Shatter and mode_sorcerer_curse_armor - armor points are restored to the original values once the mod ends.
- [x] wrong Achievements icons
First Blood icon - First Blood
Daring icon - Starry
Armageddon icon - Bloodlust
Home Improvement icon - Daring
Starry icon - What's That?
(Super Mario - icon is correct. but a space between super and mario is required.)
What's That? icon - Armageddon
Nuts and Bolt icon - Is He Dead Yeti?
Slayer icon - Nuts and Bolts
Tactician icon - Death From Above
The Architect icon - Superstar
Terminator icon - Fearless
Is He Dead Yeti? icon - Specialist
Death From Above icon - Bloodlust
Superstar icon - Tactician
This Is the End! icon - The Architect
Die Hard icon - Terminator
G.I. Joe icon - Die Hard
Fearless icon - Cannon Fodder
Cannon Fodder icon - G.I. Joe
Great Defender icon - This Is the End!
Iron Defender icon - Heroic Defender
Heroic Defender icon - Great Defender
- [x] Rangers Hideout - Thorn glitches: the druid doesn't appear and it never activates.
  - [no druid appears on thorn upgrade.txt](https://github.com/cigumo/krli/files/4129797/no.druid.appears.on.thorn.upgrade.txt)
  - https://streamable.com/vd9e3
  - I believe it was upgrade twice while paused with A dev key.
- [x] Arcane Wizard Teleport - fails to pick up fast enemies such as boosted rocket rider, because the targets still move while the portal is opening. And also fails on slow enemies such as Demon Lord or Swamp Thing. Unity version's Teleport and Faustus's Teleport don't have these problems.
- [x] Tesla - Lightning doesn't jump to targets as in cocos. It looks like love tesla doesn't jump to targets well when targets turn a corner or when they are lined up vertically.
- [x] range boost upgrades don't increase musketeer's skill ranges. 
  - the don't affect ranges in cocos
- [x] range boost upgrades don't increase ranger's thorn range.
- [x] Alleria Wildcat - change its HP to 200/400/600 (and 240/480/720 on Casual)
- [x] Alleria Wildcat - "Spiked Armor" upgrade doesn't apply to the cat.
- [x] When winged sheep is zapped by Arcane Death Ray, it shows carcass. 
  - it shows sheep death animation, that is an explosion
- [x] Werewolf and Lycan - They still regen while "thorn"-ed or freezed. 
- [x] Lycan's disease - when soldiers turn to Werwolves, they get thorned. 
- [x] "hero at your command" card on Gerald's first appearance - it should pop up upon entering the Twin Rivers. Not when battle begins.
- [x] Worg - new enemy card for this enemy doesn't pop up in silveroak forest
- [x] Gulaemon in the air - When zapped by Death Ray, a pile of ashes appear on the ground.  
- [x] Magma Elemental - death sfx is not the crumbling sound. (unity uses crumble sound.)
- [x] Gargoyle - change damage value to "none"
- [x] wizard disintegrate does not override demon death aura
- [x] level 10 (wastes) - sometimes, no skeleton spawns from the graveyard. 
  - could not reproduce
  - see #1087 
- [x] unity import fails to include levels won in veteran
  - works for me, need more feedback
  - the problem was that Unity only keeps the last difficulty played, not the highest.

## Low Prio
- [ ] in melee combat, soldier's textures are shown behind the enemy textures, obscuring cool actions from heroes.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43391939/73194623-d5a8b480-416f-11ea-9188-5cefb1e47b9b.gif)
  - not sure it will look better
- [ ] Gulaemon in the air - When polymorphed, the sheep doesn't get to have wings. 
  - requires redoing the mod as the mapping works by enemy template not status
- [ ] Tesla - it should abort attacking when there is no target in range. (overcharge shouldn't abort though.) and should re-target if another enemy is in range.
  - it is retargeting already, but it will not stop an trigger the overcharge always
- [x] Elora - missing level-up sfx on respawn
- [x] Arcane Wizard - basic attack and death ray animations dont abort when there is nothing to hit.
- [x] Arcane Wizard teleport_arcane mod - there are frames that blip and enemy textures are displayed at the same time. Hero Magnus's teleport IS perfect. 
- [x] Sorcerer - curse mod's interval isn't 30 frames but 38 frames. (like the Poison Arrow's tick interval)
  - yes, but will leave it like this. 
- [x] Sorcerer - bullet's tail appears rather soon. 
- [x] these towers have a yellow ring around the holder.
![20200126053134_1](https://user-images.githubusercontent.com/43391939/73127000-601cd700-3ffd-11ea-9c31-a7b2d42e289e.jpg)
- [x] King Denas Catapult Barrage - the number of launch sfx is too random and can exceed the actual number of bombs at early levels. (for example, 5 shots and 3 bombs. Some may wonder "where did the other bombs go?") 
  - yes, but I'll leave it like this :)
- [x] Juggernaut - Punch sfx "kr4_power_juggernaut_punch" is missing. Didn't Bolin send you the wav file?
  - waiting for wav file
- [x] Pit of Fire campaign - the sleeping Cerberus can't be selected. (Vez'nan and Moloch are selectable)
  - won't fix for now
- [x] Swamp Thing's throw sfx is not kr3_sfx_stonedruid_boulderthrow-op2.
  - I added a new squishy sound
- [x] Splat sign for instakills is over the heads of Oni and Hacksaw. Doesn't it have to be over the target's head?
- [x] Headshot sign for Sniper Shot is displayed a bit low for the big target. Adjustment needed.
- [x] freeze mod obscures curse mod.
- [x] Lord Blackburn description in encyclopedia - Remove the comma that is placed after the word "evil".
- [x] Pillager - remove "area magic attack" from the description. Or change the damage type to true. :-)
- [x] review the necromancer's bullet.
![2020_01_31_01_09_17_488_new - 1337](https://user-images.githubusercontent.com/43391939/73469038-16e7d100-43c9-11ea-92f6-51c1c8992e9f.jpg)
- [x] Ingvar - hitbox is located very low.
![20200131013306_1](https://user-images.githubusercontent.com/43391939/73469553-e0f71c80-43c9-11ea-9f96-f93aeabd7dc3.jpg)
- [x] No sfx when Lava Elemental spawns from the volcano in Forsaken Valley. I think cocos uses the elemental spawn sfx for it.
