### ISSUE TITLE
kr1-desktop - steam release checklist

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1090]
## Before Release
- [x] set launch parameters on steam
  - mac: delete default, remove beta branch
  - linux: delete default, remove beta branch
- [x] publish achievements on steam
- [x] update credits

## Before Public Beta release
- [x] rebase to master to include latest fixes in sounds
- [x] reexport sounds with new script

## Before Beta Release
- [x] test import in Linux
- [x] test import in SteamOS
- [x] enable cloud sync in Steam
- [x] set launch parameters on steam
  - mac and linux: change internal to beta branch
- [x] load achievements missing on steam ( supreme defender, sunray tower)
