### ISSUE TITLE
kr2 endless qa round Aug 2021

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1535]
**High prio**
- [x] enemies invulnerable under boss spell: #1064 
- [x] level 81/82: flying waves have no wing indicators #1536
- [x] crack in background lane level 81 https://cdn.discordapp.com/attachments/770286015646400542/877553459174469692/20210818230218_1.jpg
- [x] defeat popup showing 9999 gems always

**Localization issues:**
- [x] Tip endless localizations missing
- [x] Endless defeat comment vertical alignment: https://cdn.discordapp.com/attachments/770286015646400542/877556791720955914/20210818231552_1.jpg
- [x] Hud score/waves too small in KR: https://cdn.discordapp.com/attachments/770286015646400542/877559254133907556/20210818232612_1.jpg

**Maybe**
- [x] #1471 : Encyclopedia Boss Tag in Frontiers Mobile
- [ ] #1334
- [ ] level 81: portal sometimes has no animation while enemies are coming out
