### ISSUE TITLE
Hero ability problems

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1575]
### Universal
- [ ] Hero level up animations, start and tail end not interruptible

### KR1
**Alleria:**
- [ ] Wildcat summon, start and tail end not interruptible
- [ ] Wildcat is affected by Lycanthropy when other hero summons are not, #1586 
- [ ] Wildcat cannot be summoned or rallied onto ice, #1592

**Bolin:**
- [ ] Mines, tail end not interruptible
- [ ] Tar Bomb, tail end not interruptible

**Magnus:**
- [ ] Shadows, tail end not interruptible
- [ ] Shadows do not have Slow Curse, #1569
- [ ] Arcane Storm, tail end not interruptible

**Ignus:**
- [ ] Surge of Flames can move through Hushwood canopy, #1574
- [ ] Flaming Frenzy, tail end not interruptible.
- [ ] Surge of Flames can get Ignus stuck in unpathable spots, #1591 

**King Denas:**
- [ ] Royal Edict does not affect the actual range of level 4 artillery, even though it does affect it visually, #1497 

**Hacksaw:**
- [ ] Does not have a poison decal even though he is affected by poison, #1454 

**Thor:**
- [ ] Thunderclap misses when target dies, #1504 

**Ten'shí:**
- [ ] Iron Time has priority over walking. Same as #1559 but with walking instead of teleporting.

### KR2
**Alric:**
- [ ] Sand Warriors sometimes are not summoned, #1531 
- [ ] Sand Warriors are summoned when only burrowed Dune Terrors are near, #1015 

**Mirage:**
- [ ] Lethal Strike, start and tail end not interruptible

**Nivus:**
- [ ] Disintegration, start and tail end not interruptible
- [ ] Magic Missiles have too short a retargeting range, #998 
- [ ] Basic attack visual glitch, #997 

**Blackthorne:**
- [ ] Looting does not give bonus gold from invisible Nightscales, #1561 

**Karkinos:**
- [ ] Battle Hardened occasionally activates upon respawn, #1558 
- [ ] Battle Hardened protects against instakills, #976 
- [ ] Shoulder Cannon prediction is wonky, #1490 

**Saitam:**
- [ ] Monkey Palm has a weird interaction with Totem of Spirits, #1533 

**Kahz:**
- [ ] Can be eaten by plant during Bull Rush, #951 

**Ashbite:**
- [ ] Basic attack does not seem to target enemies in water, #1516
- [ ] Blazing Breath only deals 24/32/42 damage rather than the advertised 28/42/56.

**The Black Corsair (secondary hero on level 17, Storm Atoll):**
- [ ] Different mine placement compared to Cocos, #1522 

### KR3
**Eridan:**
- [ ] Dual Strike can be interrupted by Nimble Fencer triggering

**Catha:**
- [ ] Faery Soul seems to prioritise other units over Bolverk
- [ ] Pixie's Fury potentially dealt true damage on Cocos

**Bruce:**
- [ ] Hero spell description and effect do not match, #622 

**Reg'son**
- [ ] Eldritch Blade, start and tail end not interruptible

**Prince Denas**
- [ ] Celebrity, start and tail end not interruptible
- [ ] Passive (gold at the start of a wave), start and tail end not interruptible

**Razz and Rags:**
- [ ] Hammer time, start not interruptible, but becomes interruptible before it deals damage and is then wasted
- [ ] Kamihare, start and tail end not interruptible
- [ ] Angry Gnome, wasted when interrupted

**Bravebark:**
- [ ] Branchball, start and tail end not interruptible, #1521 
- [ ] Issues with Hyenas, #1545 

**Xin:**
- [ ] Daring Strike, start not interruptible
- [ ] Mind Over Body, start and tail end not interruptible
- [ ] Inspire, start and tail end not interruptible

**Wilbur:**
- [ ] Smokespitter, start and tail end not interruptible

**Durax:**
- [ ] Lethal Prism sfx issue, #1544 
- [ ] Hero spell would be better with big decal, #1445

**Faustus:**
- [ ] Enervation can be used on Screecher Bats but has no effect on them. Possibly another case of #1043 
- [ ] Arm disappears during teleport animation, #1375 
- [ ] Hero spell can target weird paths in Unseelie Court, https://youtu.be/uhxioRjIi8I?t=992

Disclaimer: a few of these might be incorrect observations, and the interruptibility issues might not be complete, i.e. there might be more.
