### ISSUE TITLE
KR3 A3 bugs (v0.3)

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#57]
# Pending
- [x] Restarted Shrine as Mactans tried to web, she got stuck on restart. Kinda funny really. It disappeared when Mactans tried to web again on the actual level. / AerisDraco
  - moved to cigumo/kr-love#236
- [x] Used the skip wave shortcut to play around with the final boss, and during the battle, Mactans showed up, separately from the boss, to do her web thing. / AerisDraco
  - moved to cigumo/kr-love#236
- [x] There's no units coming out after Spider Goddess is present on the field. Do not know if it's intended. / PitNata
- [x] Spider Godedess: No units are spawned from the entrances while she is active. / AerisDraco
- [x] Spider Godedess: Health threshold seems a bit weird for the jumps. The wiki says roughly 25% HP is a jump, so on Veteran she should jump at circa 13500, 9000, and 4500. However, in my playthrough, she jumped at 14K, 10K, and 6K. Not sure if this a bug though. / AerisDraco
- [x] Spider Goddess jumps, hp number can be higher then what damage she was dealt before hand. For example, I damaged her to about 9K HP while she charged the Tear to destroy a tower. However, when she landed again, she had 10K HP. / AerisDraco

# TBD with Ironhide
- [x] Eridan was able to heal himself during his ranged attacks on mobile, now he doesn't gain any health. Intentional or not, do not know either. / PitNata
  - moved to cigumo/kr-love#226
  - in general, all attacks interrupt regen (this.regen.last_hit_standoff_time and oothers). think about this.
- [x] Pixie's Fury upon hit, put's enemies to sleep which is not written in description of the spell. do not know if it's intentional. / PitNata
  - code suggests it should curse, but playing does not work. ask. 
  - moved to cigumo/kr-love#226

# Fixed in v0.9
## screen_map
- [x] Hero Portrait Text seems duplicated on all heroes / AerisDraco
- [x] Vez'nan's Text is miscolored / AerisDraco
- [x] For some reason, the names written in Hero rooms displayed twice, and overlaps. Vez'nan's name is written in a different color than initial. / PitNata
 
## misc
- [x] The High Elven Mages Timelapse has a chance to freeze enemies entirely. The enemies cant move at all but they cant be targeted by towers. / SealDarklight  (duplicate #50)
- [x] Iron Mactan's Retreat Wave starts a lot later (in other words, you have to wait for enemies to come out) / PitNata
  - checked and it's identical to mobile. the first enemy is a golem and appears long after a lot of spiders have spawned
- [x] Heroic Mactan's Retreat third wave one of the wave pointers does not show any enemies coming from that path. / PitNata
- [x] Alleria and Gnoll Catapult names are not written (Hero_Alleria_Name; Enemy_Catapult_Name is written instead) / PitNata
- [x] Wild Magus Ward of Disruption seems to disable attacking capabilities as well for Gnoll Blighters. Do not know if it's intentional. / PitNata
- [x] Scourger's Banshee can be fooled into entering towers that are still constructing. Banshee does stuns the tower, but will not affect anything, after tower is being completed. / PitNata
- [x] Scourger's Banshee can be escaped if you upgrade the tower exact time when banshee is entering a building. / PitNata
- [x] Scourger's Banshee plays dying sound of a soldier when it "dies" (In other words, when either it enters a building or when it reached the end of the path) / PitNata
- [x] Scourger Ghosts seem to move more slowly. / AerisDraco
- [x] In mobile, Perythons carrying gnolls would drop them ASAP if there's any soldier or hero nearby, on PC, it will drop it when it dies. if it's intentional or not, not sure. / PitNata
- [x] In Iron Challenge of Aredhel Gardens, you're able to upgrade to Forest Keepers, do not know if it's intentional. / PitNata
- [x] Hints on either Heroic or Iron challenges show up everytime you start them. Do not know if it's intentional. / PitNata
- [x] Zealots have improper name and has no max health paramater (but it does have it's current health) / PitNata
- [x] Sorcerer Stones have a tendency having strange animation disruptions when it tries to enhance towers. It seems it either does the whole animation, or ends it before it is finished. The effect of the towers still applies on both cases. / PitNata
- [x] Young Ashbite seems to attack faster than in mobile. not sure if it's intended. Also, the name is improper too (Name_) / PitNata
- [x] Ashbite Deals about 83-125 compair in the ashbites description to the typical 40-60 / SealDarklight
- [x] Ashbites Dragon Nest description says that Ashbite deals 0-0 damage / SealDarklight
- [x] Young Beresad burns the whole path a lot slower than in mobile, a LOT slower. Not sure if it's a feature. / PitNata
- [x] Wild Magus now can make Twilight Golems explode, unlike in mobile. Not sure if it's a feature. / PitNata
- [x] Mages will not stop their attack charging or changing targets, if it's own current target is out of range. If it has teleported, the Magic projectiles will follow the target until they hit. / PitNata
- [x] If a frozen unit gets blown up by Magus's explosion skill, Animation does not play, they will simply vanish. / PitNata
- [x] Some portraits when selected is missing, the druid portrait resembles Desert Thug enemy from Kingdom Rush: Frontiers. (Not finished yet?) / PitNata
- [x] Twilight Golem can be instakilled (One shot killed by Crimson Sentence and Eldrich Doom can target it) / SealDarklight

## sound
- [x] There's no sound playing when the enigmatic transformation of both Malicia and Mactans takes place (the only sound which you can hear is the statue crumbling, nothing else, background music still plays.) / PitNata
- [x] Sound of rocks becoming a boulder does not play for the Druids. / PitNata

## fx/taunts/screens
- [x] The "secret" comic, does not play it's own sound, it does play the background music of the First City. / PitNata
- [x] Mactans and Malicia in Shrine of Elynie exchanged some quotes (In particular "Oh dear. What an awkward situation" belongs to Malicia, but Mactans say it, or "Don't Think Too Much. You'll die either way." Which Malicia says but Mactans should say that instead) / PitNata
- [x] Second Comic's "Twilight" word is too big to fit into the talking cloud. / PitNata

## achievements
- [x] It's A Trap achievement (prevent Mactans from webbing 8 towers) triggered when I prevented her from webbing the path / AerisDraco
- [x] Game gives you star collecting achievement when you complete the first mission up to "Starcraft" even though you haven't collected all of them (Tested on a clean second save) / PitNata

## engine
- [x] Serious frame rate issues when too many units are onscreen. This was on later waves of Shrine of Elynie, where large amounts of Harassers and spiders spawned. / AerisDraco, PitNata (moved to #59)
- [x] If you switch windows vice versa, on some occasion the game will simply show the black screen instead (the game still respond to the mouse, as well as game continues as normal) / PitNata ( moved to #60)

## heroes
- [x] Xin's Daring Strike, it does not allow him to teleport him during his *phasing* animation anymore, although it's still possible to move him to other platforms with precise timing (it will walk instead of teleporting the exact location) / PitNata
- [x] Xin Using Daring Strike while rally pointing allows Xin to walk to the islands instead of teleporting (Used in Arcane Quarters) / SealDarklight
- [x] Catha's Hero spell not written properly (The code is written instead) / PitNata
- [x] Catha tries to summon pixies, even though the doesn't have any points in Fairy Tale. After summoning, she is stucked and not able to move(Pixies are not summoned either, but the animation still played) / PitNata
- [x] Catha's Passive Skill when activated, does put the enemy to sleep indefinitely, if she keeps attacking the same unit, do not know if it's intentional. / PitNata
- [x] Cathas Faery Dust SPELL doesnt work on flying enemies and only works on enemies on ground / SealDarklight
- [x] Flying units are immune to Catha's Hero Spell. / PitNata
- [x] Eldritch Heal skill tab is looking differently than other skills (in other words, it has improper colour) / PitNata
- [x] Vez'nan pulls out his Arcane Nova every second shot he does / PitNata

# won't fix
- [x] The Venom Vine near Rockhenge does the usual animation, but the return to it's "full" or ready state is too fast / AerisDraco
- [x] The Sorcerer's Broom from Arcane Quarters is on the map, but it is closer to the level flag for The Ascent then it is to Arcane Quarters. / AerisDraco
- [x] Gnoll Catapults are invicible when moving, do not know if it's intentional. / PitNata
- [x] Blade Dance seems it deals true damage. Do not know if it's intentional. / PitNata
  - yes
- [x] Iron Crystal Lake does not grant you ability to upgrade to Weirdwoods, unlike in Mobile. Do not know if it's intentional. / PitNata
  - it's the same as in mobile. weirdwoods are unlocked in stage 10
- [x] In the last comic, the "Victory" word does not appear unlike it is on Mobile. Not sure if it's an enhancement. / PitNata
  - removed in i18n pass

# hardware specs
- PitNata: I run under Windows 7, on a HD graphics, 60 fps, 1600x900 resolution.
- AerisDraco: AMD FX8800 Radeon R7, 2.1GHz, 16GB, 8GB vram, 64bit
